language: php

php:
  - 5.6

dist: bionic

env:
  global:
    - PHPBB_TAG="release-3.3.0"
    - PHPBB_VERSION="3.3"
    - PHPBB_LANGUAGE="sr"

before_install:
  - rm -rf $PHPBB_VERSION
  - mkdir -p $PHPBB_VERSION/en/language
  - mkdir -p $PHPBB_VERSION/en/styles/prosilver/theme
  - mkdir -p $PHPBB_VERSION/$PHPBB_LANGUAGE/language
  - mkdir -p $PHPBB_VERSION/$PHPBB_LANGUAGE/styles/prosilver/theme
  - git clone --branch $PHPBB_TAG "https://github.com/phpbb/phpbb.git"
  - cp -r phpbb/phpBB/language/en $PHPBB_VERSION/en/language
  - cp -r phpbb/phpBB/styles/prosilver/theme/en $PHPBB_VERSION/en/styles/prosilver/theme
  - curl -sS "https://getcomposer.org/installer" | php

install:
  - php composer.phar install --no-interaction --prefer-source

script:
  - ./build.py
  - cp -r build/language/$PHPBB_LANGUAGE $PHPBB_VERSION/$PHPBB_LANGUAGE/language/$PHPBB_LANGUAGE
  - cp -r build/styles/prosilver/theme/$PHPBB_LANGUAGE $PHPBB_VERSION/$PHPBB_LANGUAGE/styles/prosilver/theme/$PHPBB_LANGUAGE
  - php vendor/bin/translation.php validate $PHPBB_LANGUAGE --phpbb-version=$PHPBB_VERSION --display-notices
